backendStore:
  databaseMigration: true
  postgres:
    enabled: true
    host: "{{ host_db }}"
    port: 5432
    database: "{{ db_name }}"
    user: "{{ db_user }}"
    password: "{{ db_password }}"
artifactRoot:
  s3:
    enabled: true
    bucket: '{{ MINIO_SECOND_BUCKET_NAME }}'
    awsAccessKeyId: '{{ MINIO_ROOT_USER }}'
    awsSecretAccessKey: '{{ MINIO_ROOT_PASSWORD }}'
# correct this
extraEnvVars:
  MLFLOW_S3_ENDPOINT_URL: http://minio.com
serviceMonitor:
  enabled: true
