airflowHome: /opt/airflow
airflowVersion: "2.6.2"

executor: KubernetesExecutor

dags:
  gitSync:
    enabled: true
    repo: https://github.com/Danil-Sharipov/First_in_MLOps.git
    branch: main
    subPath: "dags"

images:
  airflow:

   repository: airflow-image
   tag: 1.0.0

  redis:
    repository: redis
    tag: 7-bullseye
    pullPolicy: IfNotPresent

airflow:
  usersUpdate: true

  users:
    - username: {{ username }}
      password: {{ password }}
      role: Admin
      email: {{ email }}
      firstName: {{ firstName }}
      lastName: {{ lastName }}

  extraPipPackages:
    - "airflow-exporter~=1.4.1"

  config:
    AIRFLOW__SCHEDULER__DAG_DIR_LIST_INTERVAL: 60
    AIRFLOW__CORE__LOAD_EXAMPLES: "False"

  persistence:
    enabled: true
    storageClass: default
    accessMode: ReadOnlyMany
    size: 1Gi

workers:
  replicas: 1

  resources:
    requests:
      memory: "2Gi"

scheduler:
  
  replicas: 1

  command: ~
  args: ["bash", "-c", "exec airflow scheduler"]

  livenessProbe:
    initialDelaySeconds: 10
    timeoutSeconds: 20
    failureThreshold: 5
    periodSeconds: 60

  waitForMigrations:
    enabled: false

postgresql:
  enabled: false

data:
  metadataConnection:
    user: {{ user_db }}
    pass: {{ pass }}
    protocol: postgresql
    host: {{ host }}
    port: 5432
    db: {{ db }}
    sslmode: disable

webservers:
  defaultUser:
    enabled: true
    username: {{ username }}
    password: {{ password }}
    role: Admin
    email: {{ email }}
    firstName: {{ firstName }}
    lastName: {{ lastName }}
env:
  - name: "MINIO_BUCKET_NAME"
    value: "{{ MINIO_BUCKET_NAME }}"
  - name: "MINIO_ROOT_USER"
    value: "{{ MINIO_ROOT_USER }}"
  - name: "MINIO_ROOT_PASSWORD"
    value: "{{ MINIO_ROOT_PASSWORD }}"
