---
- hosts: db_nodes
  become: true
  gather_facts: false
  roles:
    - postgresql
- hosts: k3s_nodes
  strategy: free
  become: true
  gather_facts: false
  roles:
    - k3s-base
- hosts: master_nodes
  become: true
  gather_facts: false
  roles:
    - k3s-server
- hosts: worker_nodes
  strategy: frees
  become: true
  gather_facts: false
  roles:
    - k3s-agent
- hosts: master_nodes
  become: true
  gather_facts: false
  roles:
    - minio
    - mlflow