---
- hosts: db_nodes
  become: true
  gather_facts: false
  roles:
    - postgresql
- hosts: k3s_nodes
  strategy: free
  become: true
  gather_facts: false
  roles:
    - k3s-base
- hosts: master_nodes
  become: true
  gather_facts: false
  roles:
    - k3s-server
#    - minio
#    - mlflow
- hosts: worker_nodes
  strategy: debug
  become: true
  gather_facts: false
  vars:
    host: "192.168.56.10"
  roles:
    - k3s-agent