image:
  repository: quay.io/minio/minio
  tag: RELEASE.2023-10-07T15-07-38Z
  pullPolicy: IfNotPresent
buckets:
  - name: '{{ defaultBuckets }}'
    objectLock: false
    region: us-east-1
#users:
#  CONSOLE_ACCESS_KEY: '{{ rootUser }}'
#  CONSOLE_SECRET_KEY: '{{ rootPassword }}'
stringData:
  config.env: | -
    export MINIO_ROOT_USER='{{ rootUser }}'
    export MINIO_ROOT_PASSWORD='{{ rootPassword }}' 