secrets:
  name: myminio-env-configuration
  accessKey: minio
  secretKey: minio123
tenant:
  buckets:
    - name: {{ defaultBuckets }}
  pools:
    - servers: 1
      name: pool-0
      volumesPerServer: 1
      size: 1Gi
      storageClassName: local-path
ingress:
  api:
    enabled: false
    host: minio.com
    path: /api
    pathType: Prefix
    annotations:
      ingress.kubernetes.io/ssl-redirect: "false"
  console:
    enabled: true
    host: minio-console.com
    path: /console
    pathType: Prefix
    annotations:
      ingress.kubernetes.io/ssl-redirect: "false"
