secrets:
  name: myminio-env-configuration
  accessKey: "{{ rootUser }}"
  secretKey: "{{ rootPassword }}"
tenant:
  buckets:  
    - name: {{ defaultBuckets }}
  pools:
    - servers: 1
      name: pool-0
      volumesPerServer: 1
      size: 1Gi
      storageClassName: local-path
  metrics:
    enabled: true
    port: 9000
    protocol: http
#ingress:
#  api:
#    enabled: true
#    host: minio.com
#    path: /api
#    pathType: Prefix
#    annotations:
#      ingress.kubernetes.io/ssl-redirect: "false"
#  console:
#    enabled: false
#    host: minio-console.com
#    path: /console
#    pathType: Prefix
#    annotations:
#      ingress.kubernetes.io/ssl-redirect: "false"
