apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myminio-console
  namespace: tenant-ns
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
spec:
  tls:
    - secretName: myminio-tls
  rules:
    - host: minio-console.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: myminio-console
                port:
                  number: 9443
    - host: minio.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: minio
                port:
                  number: 443
    - host: minio-hl.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: myminio-hl
                port:
                  number: 9000