apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myminio
  namespace: tenant-ns
spec:
  ingressClassName: nginx
  rules:
    - host: minio.local
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: minio
                port:
                  name: http
          - path: /console
            pathType: Prefix
            backend:
              service:
                name: myminio-console
                port:
                  name: http
