---
- name: 'Download k3s binary'
  shell:
    cmd: /usr/local/bin/k3s-install.sh
  environment:
    INSTALL_K3S_SKIP_START: "true"
    INSTALL_K3S_EXEC: "agent"
  changed_when: true
- name: 'Init cluster'
  register: marker
  template:
    src: k3s-agent.service.j2
    dest: '{{ systemd_dir }}/k3s-agent.service'
    owner: root
    group: root
    mode: 0644
    force: true
- name: Enable and check K3s service
  systemd:
    name: k3s-agent.service
    daemon_reload: "{{ true if marker.changed else false}}"
    state: "{{ 'restarted' if marker.changed else 'started' }}"
    enabled: true