version: "3.8"
services:
  s3:
    image: minio/minio:latest
    ports:
      - 9000:9000
      - 9001:9001
    env_file:
      - .env
    healthcheck:
      test: [ 'CMD', 'curl', 'http://airflow-s3:9000/minio/health/cluster/read' ]
      start_period: 10s
      timeout: 5s
      interval: 3s
      retries: 100
    command: server --console-address ":9001" /data