apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: mldemo
  name: mldemo
  namespace: ml-ns
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mldemo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mldemo
    spec:
      containers:
        - image: project:v1
          name: mldemo
          resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: lb-service
  namespace: ml-ns
  labels:
    app: lb-service
spec:
  type: LoadBalancer
  ports:
    - port: 5000
      targetPort: 5000
  selector:
    app: mldemo
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lb-service
  namespace: ml-ns
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
    - host: ml.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: lb-service
                port:
                  number: 5000