---
- name: 'Add minio-operator chart repo'
  kubernetes.core.helm_repository:
    name: minio-operator
    repo_url: https://operator.min.io/
- name: 'Deploy minio by helm chart'
  kubernetes.core.helm:
    name: operator
    chart_ref: minio-operator/operator
    namespace: minio-operator
    create_namespace: true
    force: true
  environment:
    KUBECONFIG: /etc/rancher/k3s/k3s.yaml
- name: 'Deploy minio tenant'
  kubernetes.core.helm:
    name: tenant
    chart_ref: minio-operator/tenant
    namespace: tenant-ns
    create_namespace: true
    force: true
    wait: True
    update_repo_cache: True
    values: "{{ lookup('template', 'values.yaml') | from_yaml }}"
  environment:
    KUBECONFIG: /etc/rancher/k3s/k3s.yaml

# А зачем?
#- name: "Get data"
#  shell: |
#    kubectl get secrets/myminio-tls -o jsonpath={.data} -n tenant-ns |jq -r '."private.key"' | base64 --decode > /tmp/key
#    kubectl get secrets/myminio-tls -o jsonpath={.data} -n tenant-ns |jq -r '."public.crt"'  | base64 --decode > /tmp/cert
#    kubectl create secret tls myminio-secret --cert=/tmp/cert --key=/tmp/key -n tenant-ns


- copy:
    src: ingress.yaml
    dest: /tmp/ing.yaml
- name: 'Apply manifest to the cluster'
  kubernetes.core.k8s:
    state: present
    src: /tmp/ing.yaml
  environment:
    KUBECONFIG: /etc/rancher/k3s/k3s.yaml
- file:
    state: absent
    path: /tmp/ing.yml


- name: 'Update /etc/host'
  block:
    - lineinfile:
        insertbefore: BOF
        path: /etc/hosts
        line: '{{ item }}'
      with_items:
        - '192.168.56.10 minio-console.com'
        - '192.168.56.10 minio.com'
        - '192.168.56.10 minio-hl.com'

- name: install pre-requisites
  pip:
    name:
      - minio
      - requests
      - pandas


- name: 'migrate'
  block:
    - name: 'migrate file'
      template:
        src: migrate.py.j2
        dest: '/tmp/migrate.py'
        owner: root
        group: root
        mode: 0644
    - name: 'python3 test'
      command:
        cmd: 'python3 /tmp/migrate.py'
    - name: 'delete migration script'
      file:
        state: absent
        path: /tmp/migrate.py