---
- name: 'Add mlflow-operator chart repo'
  kubernetes.core.helm_repository:
    name: community-charts
    repo_url: https://community-charts.github.io/helm-charts

# вроде бы хорошо подключилась к s3, но к database? вообще подключение работает
- name: 'Deploy mlflow by helm chart'
  kubernetes.core.helm:
    name: mlflow
    chart_ref: community-charts/mlflow
    namespace: mlflow-ns
    create_namespace: true
    force: true
    values: "{{ lookup('template', 'values.yaml') | from_yaml }}"
  environment:
    KUBECONFIG: /etc/rancher/k3s/k3s.yaml
- copy:
    src: ingress.yaml
    dest: /tmp/ing.yaml
- name: 'Apply manifest to the cluster'
  kubernetes.core.k8s:
    state: present
    src: /tmp/ing.yaml
  environment:
    KUBECONFIG: /etc/rancher/k3s/k3s.yaml
- file:
    state: absent
    path: /tmp/ing.yml
- name: 'Update /etc/host'
  block:
    - lineinfile:
        insertbefore: BOF
        path: /etc/hosts
        line: "192.168.56.10 mlflow.com"