---
- local_action: command ansible-playbook Dockerfiles/airflow/playbook.yml
  become: false
- stat:
    path: '/tmp/airflow.tar'
  register: check
# check block
- name: 'Image install'
  when: check.stat.exists == False
  block:
    - name: 'Copy file'
      copy:
        src: airflow.tar
        dest: /tmp/airflow.tar
    - command:
        cmd: k3s ctr images import /tmp/airflow.tar


- name: 'Add airflow chart repo'
  kubernetes.core.helm_repository:
    name: apache-airflow
    repo_url: https://airflow.apache.org
    force_update: yes
#
- name: 'Deploy airflow by helm chart'
  kubernetes.core.helm:
    name: airflow
    chart_ref: apache-airflow/airflow
    namespace: airflow-ns
    create_namespace: true
    force: true
    update_repo_cache: True
#    wait: True
    values: "{{ lookup('template', 'values.yaml') | from_yaml }}"
  environment:
    KUBECONFIG: /etc/rancher/k3s/k3s.yaml
  ignore_errors: true

- copy:
    src: ingress.yaml
    dest: /tmp/ing.yaml
- name: 'Apply manifest to the cluster'
  kubernetes.core.k8s:
    state: present
    src: /tmp/ing.yaml
  environment:
    KUBECONFIG: /etc/rancher/k3s/k3s.yaml
- file:
    state: absent
    path: /tmp/ing.yml
- name: 'Update /etc/host'
  block:
    - lineinfile:
        insertbefore: BOF
        path: /etc/hosts
        line: "192.168.56.10 aiflow.com"



