---
- name: 'Add airflow chart repo'
  kubernetes.core.helm_repository:
    name: apache-airflow
    repo_url: https://airflow.apache.org

- name: 'Deploy airflow by helm chart'
  kubernetes.core.helm:
    name: airflow
    chart_ref: apache-airflow/airflow
    namespace: airflow-ns
    create_namespace: true
    force: true
#    values: "{{ lookup('template', 'values.yaml') | from_yaml }}"
  environment:
    KUBECONFIG: /etc/rancher/k3s/k3s.yaml




- copy:
    src: ingress.yaml
    dest: /tmp/ing.yaml
- name: 'Apply manifest to the cluster'
  kubernetes.core.k8s:
    state: present
    src: /tmp/ing.yaml
  environment:
    KUBECONFIG: /etc/rancher/k3s/k3s.yaml
- file:
    state: absent
    path: /tmp/ing.yml
- name: 'Update /etc/host'
  block:
    - lineinfile:
        insertbefore: BOF
        path: /etc/hosts
        line: "192.168.56.10 aiflow.com"