---
- hosts: master_nodes
  gather_facts: false
  become: true
  tasks:
#    - lineinfile:
#        insertbefore: BOF
#        path: /etc/hosts
#        line: "192.168.56.10 minio.com"
    - command:
        cmd: kubectl get nodes
      register: check
      environment:
        KUBECONFIG: /etc/rancher/k3s/k3s.yaml
    - debug:
        msg: "{{ check.stdout }}"
    - command:
        cmd: kubectl get ing -n tenant-ns
      register: check
      environment:
        KUBECONFIG: /etc/rancher/k3s/k3s.yaml
    - debug:
        msg: "{{ check.stdout }}"
    - command:
        cmd: curl -k https://minio.com/console
      register: check
    - debug:
        msg: "{{ check.stdout }}"
    - command:
        cmd: cat /etc/hosts
      register: check
    - debug:
        msg: "{{ check.stdout }}"
